name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    -main
    -'*'
  pull_request:
    branches:
    -main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Heure de commencement de la pipeline.
        run: echo "Heure de commencement de la pipline $(TZ='Europe/Paris' date +'%H:%M:%S')"

      - name: Installation de npm
        run: npm install

      - name: Formattage avec prettier
        run: npm run prettier:fix

      - name: formattage avec lint
        run: npm run lint:fix
        
      - name: Test du code
        run: npm run test

      - name: Test du coverage
        run: npm run test:coverage

      - name: build le code 
        run: npm run build

      - name: Heure de fin de la pipeline.
        run: echo "Heure de fin de la pipline $(TZ='Europe/Paris' date +'%H:%M:%S')"

      - name: Affichage du message de succès
        if: failure() == false
        run: echo "PIPELINE SUCCESS WITHOUT ERRORS"
